config:
  template_path: templates
  template_name: base.html

  images_path: images

  # Font sizes always in pixels
  font:
    normal_size: 16
    license_size: 12

  width:
    max: 640px
    min: 420px
    name: 6em
    value: 6em
    units: 6em
    comment: 20em
  
  onload: setup()
  
  resolution: 5
