config:
  template_path: templates
  template_name: base.html

  include_path: include
  images_path: images

  font:
    normal_size: 16px
    license_size: 12px

  width:
    max: 640px
    min: 420px
    name: 6em
    value: 6em
    units: 6em
    comment: 20em

  resolution: 5
